---
extends: default

rules:
  document-start:
    level: warning
  line-length:
    max: 120
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
    level: warning
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  trailing-spaces: enable
  new-line-at-end-of-file: enable
